FROM python:3.10-slim

WORKDIR /app

COPY backend/requirements.txt ./
RUN apt-get update && apt-get install -y ffmpeg && \
    pip install --no-cache-dir -r requirements.txt

COPY backend/ ./

EXPOSE 5000
CMD ["python", "app.py"]